// <auto-generated />
using System;
using Estacionamiento.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estacionamiento.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(EstacionamientoDbContext))]
    partial class EstacionamientoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Estacionamiento.Dominio.Estancias.Estancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ImporteCobrado")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("Salida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId", "Salida");

                    b.ToTable("Estancias", (string)null);
                });

            modelBuilder.Entity("Estacionamiento.Dominio.Vehiculos.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaDeAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Placa");

                    b.Property<string>("TipoDeVehiculo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos", (string)null);

                    b.HasDiscriminator<string>("TipoDeVehiculo").HasValue("Vehiculo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Estacionamiento.Dominio.Vehiculos.VehiculoNoResidente", b =>
                {
                    b.HasBaseType("Estacionamiento.Dominio.Vehiculos.Vehiculo");

                    b.HasDiscriminator().HasValue("NoResidente");
                });

            modelBuilder.Entity("Estacionamiento.Dominio.Vehiculos.VehiculoOficial", b =>
                {
                    b.HasBaseType("Estacionamiento.Dominio.Vehiculos.Vehiculo");

                    b.HasDiscriminator().HasValue("Oficial");
                });

            modelBuilder.Entity("Estacionamiento.Dominio.Vehiculos.VehiculoResidente", b =>
                {
                    b.HasBaseType("Estacionamiento.Dominio.Vehiculos.Vehiculo");

                    b.Property<int>("MinutosAcumulados")
                        .HasColumnType("int")
                        .HasColumnName("MinutosAcumulados");

                    b.HasDiscriminator().HasValue("Residente");
                });

            modelBuilder.Entity("Estacionamiento.Dominio.Estancias.Estancia", b =>
                {
                    b.HasOne("Estacionamiento.Dominio.Vehiculos.Vehiculo", "Vehiculo")
                        .WithMany("Estancias")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Estacionamiento.Dominio.Vehiculos.Vehiculo", b =>
                {
                    b.Navigation("Estancias");
                });
#pragma warning restore 612, 618
        }
    }
}
